version: "3.2"
services:
  nodejs:
    build: 
      context: .
    image: thefarshad/nodejs-backend
    networks:
      - frontend
      - backend
    environment:
      - MYSQL_HOST=mySQL-host
      - MYSQL_USER=mySQL-username
      - MYSQL_PASS=mySQL-password
      - MYSQL_DB=shopping_store
    volumes:
      - ./www/:/var/www/html/
    ports:
      - "8080:3000"
    container_name: nodejs-container
  mysql:
    image: mysql:5.7
    networks:
      - backend
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=mySQL-username
      - MYSQL_PASSWORD=mySQL-password
      - MYSQL_DATABASE=shopping_store
    container_name: mySQL-host
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0
    depends_on:
      - mysql
    networks:
      - backend
    ports:
      - "3306:80"
    environment:
      - PMA_HOST=mySQL-host
      - PMA_PORT= 3306
    volumes:
      - /sessions
    container_name: phpmyadmin-container
networks:
  frontend:
  backend: